### ISSUE TITLE
Notify members prior to auto renew 

### ISSUE THREAD

**Issue by julielerman** [dotnet-foundation/wg-membership#1]
Perhaps I signed up for a recurring membership, but was surprised to get an email this morning that said "here's your invoice for your $100 membership renewal". Fortunately, I'm still in a position that this is not a financial hardship. However, I think that when you move off of open collective, you should ensure that renewals are opt in (or at least opt out!) and some type of notification is sent out prior to the automatic renewal.

**Comment by wordshaker** [comment]
Membership dues are now voluntary. As such this is no longer an issue
