### ISSUE TITLE
Update Become a Member Page

### ISSUE THREAD

**Issue by wordshaker** [dotnet-foundation/wg-membership#100]
## Brief Summary of idea

The `Become A Member Page` on the .NET Foundation website needs updating https://dotnetfoundation.org/membership/become-a-member

- [x] Update form link
- [x] Update information about how to sign up to be a member of the .NET Foundation

## Aims / Benefits

To give people accurate information about how to sign up and enable signups.

## Requirements

Need a new form and new Excel that the .NET Foundations Membership Committee can review each month

**Comment by wordshaker** [comment]
I have edited the pages content but need the form link to be updated once we've agreed on it's content

https://dotnetfoundation.org/membership/become-a-member

**Comment by nicoleabuhakmeh** [comment]
We can maybe embed maybe? 

<iframe width="640px" height="480px" src="https://forms.office.com/r/uuz2pXSb4D?embed=true" frameborder="0" marginwidth="0" marginheight="0" style="border: none; max-width:100%; max-height:100vh" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>

I also update the form and here is the link: https://forms.office.com/r/uuz2pXSb4D
