### ISSUE TITLE
Customize discord invite url

### ISSUE THREAD

**Issue by codehippie1** [dotnet-foundation/wg-membership#104]
## Brief Summary of idea

DNF discord invite url maybe customized to include "dotnet-foundation"

## Aims / Benefits

Easy to communicate and remember

![Screenshot_20230302_075134_Chrome.jpg](https://user-images.githubusercontent.com/18332214/222434418-a083797e-7f72-4899-bf08-46eafbe2a0a2.jpg)

**Comment by nicoleabuhakmeh** [comment]
Just checked to see if I had the permissions to set this, I don't. This may need to be an admin and not a mod that makes this change.

**Comment by wordshaker** [comment]
![image](https://user-images.githubusercontent.com/13496774/230047341-ffe6ae54-4159-4e91-a415-5753ebbe9219.png)
