### ISSUE TITLE
A CFP (Call for proposal) page on DNF website

### ISSUE THREAD

**Issue by codehippie1** [dotnet-foundation/wg-membership#105]
## Brief Summary of idea

Currently the DNF website has a speaker list. If we build a page with CFPs, it would be easy to match speakers with group organizers. (On similar patterns of MVP CFPs in Microsoft MVP channels)

## Aims / Benefits

Increase visibility of DNF

## Requirements

A new page similar to the speaker list should be designed.

**Comment by wordshaker** [comment]
Might be more for the Outreach committee. What do you think @jguadagno ?

**Comment by jguadagno** [comment]
Sounds like a good idea.  I'll add to the https://github.com/dotnet-foundation/wg-outreach/issues
