### ISSUE TITLE
Looking to join the committee

### ISSUE THREAD

**Issue by jorgelevy** [dotnet-foundation/wg-membership#116]
## Name:
Jorge Levy

## Name:
[jorgelevy](https://github.com/jorgelevy)

## Interests:
Looking to contribute to the organization and this committee looks like a good option. Additionally, I am interested in promoting the participation of more people in different regions, especially in Latam.

**Comment by nicoleabuhakmeh** [comment]
Action is complete, Jorge has been forwarded the meeting series in outlook.
