### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by escovask8** [dotnet-foundation/wg-membership#119]
## Name:

Victor Dutra Oliveira

## Handles:

- GitHub: escovask8
- Discord: Paciente_Zer0#8494

## Interests:

_What do you think you can contribute to the committee? What are your interest areas?_

Hi,

I'm writing to express my interest in joining the .NET Foundation committee. I'm a software analyst with a passion for the .NET platform. I've been analyst software for over 3 years, and I'm currently working as a consultant.

I believe I can contribute to the committee by sharing my knowledge and experience with other developers. I'm also interested in helping to make the .NET ecosystem more accessible and friendly for developers of all levels of experience.

I'm particularly interested in the following areas:

Web development with ASP.NET Core (Basics)
Desktop development with Windows Forms and WPF (Basic)
Integration of Microsoft Azure technologies with .NET applications
SQL Server 2016 and 2019
I'm confident that I can be a valuable member of the committee, and I'm excited to contribute to the .NET ecosystem.

Thanks for your time and consideration.

**Comment by wordshaker** [comment]
@nicoleabuhakmeh can we add Victor to the meeting invites please :)

**Comment by nicoleabuhakmeh** [comment]
Hi [escovask8](https://github.com/escovask8) - I've forwarded the invite to your gmail listed on your github account.

**Comment by escovask8** [comment]
Hi, Sorry about my mistake.
I applied in the wrong place, I want to learn C# and dotnet and improve my
skills.
I think  this application is for more expecialist people.
I'm really sorry to waste your time guys.

Em qua., 9 de ago. de 2023 4:13 PM, Jessica White ***@***.***>
escreveu:
