### ISSUE TITLE
Agenda - January 2024 Meeting

### ISSUE THREAD

**Issue by nicoleabuhakmeh** [dotnet-foundation/wg-membership#129]
The Membership Committee will be having their monthly meeting on January 3, 2024 at 3pm Eastern.

Discord link is open to current members of the Membership Committee to meeting: [https://discord.com/events/966483029830824008/1175074291344232479](https://discord.com/events/966483029830824008/1175074291344232479)

To be invited to the Membership Committee on Discord, please Message below or on Discord in the Membership #discussions.

## Agenda Items

1. Applications - New Form for 2024 Membership Submissions
* 
2. Membership is now at 788 Members on Github as all Approved applications from 2023 were added. Individuals that had joined Discord were given their purple color coordination on Discord and added to Committees they asked for. 
*

3.

**Comment by jorgelevy** [comment]
Skipping this one. Still on vacation mode, see you next month. 

I can help with some membership application reviews during the month.
