### ISSUE TITLE
New Membership Committe Request

### ISSUE THREAD

**Issue by apsthisdev** [dotnet-foundation/wg-membership#139]
## Your name: 
Amey Subhedar

## Your GitHub Name or Email: 
apsthisdev

## Current Role
Senior Director, Software, Engineering & Technology Adoption at Advantest.

## Notes (OPTIONAL):
Over 10+ years in .NET ecosystem and currently As a Senior Director,  I am driving the Semiconductor and Technology value chain for Hardware, Software, Distributed Systems, HPC. .NET is a prominent ecosytem for on-prem and highly secured factory deployments. This membership will help me bring in the insights and help contribute the .NET evolution for High Tech silicon + semiconductor value chain.

**Comment by codehippie1** [comment]
@apsthisdev  Sorry for not seeing this yet. The membership committee meetings are open to members and would be the best place to start. Generally, no separate approval is needed to start engaging with the committee once you are a DNF member.
