### ISSUE TITLE
Setting up nomination committee for elections

### ISSUE THREAD

**Issue by wordshaker** [dotnet-foundation/wg-membership#20]
## Brief Summary of idea

It's been agreed that the process for this year's board elections will again include the involvement of a nominating committee. The membership committee will suggest and approach candidates to take part in the nominating committee. 

## Aims / Benefits

Reading the nominating committee ready for the board elections

## Considerations

- When reaching out to potential members of the nominating committee, be sure to explain that nominating committee members can't stand for election.
- We need to reach out underrepresented geographies and groups for the nominating committee to encourage members of those groups and geographies to run for board seats

## Requirements

- [ ] Membership committee is agreed on who should be approached.
- [ ] Nomination committee is set up ready for board elections.
- [ ] Responsibilities of the nomination committee are agreed upon, transparent and clear.
- [ ] Timeline for the committees' involvement in the board elections is transparent and clear.

**Comment by wordshaker** [comment]
@BillWagner in the timeline proposal notes there was a bullet point of `We need to reach out underrepresented geographies and groups for the nominating committee to encourage members of those groups and geographies to run for board seats`

Maybe Dhananjay Kumar might be good for the nomination committee? As he runs such large communities in India?

**Comment by jguadagno** [comment]
> @BillWagner in the timeline proposal notes there was a bullet point of `We need to reach out underrepresented geographies and groups for the nominating committee to encourage members of those groups and geographies to run for board seats`
> 
> Maybe Dhananjay Kumar might be good for the nomination committee? As he runs such large communities in India?

I would second DJ, assuming he does not want to run for the board again.

**Comment by wordshaker** [comment]
Good news @jguadagno - I had a chat with DJ and he said he'd be interested in being part of the committee 👍🏼

**Comment by wordshaker** [comment]
@BillWagner when is the deadline for putting a nominating committee together? And to put dates to the timeline proposal?

**Comment by khalidabuhakmeh** [comment]
What are the time commitment expectations from folks joining the nomination committee?

**Comment by BillWagner** [comment]
> What are the time commitment expectations from folks joining the nomination committee?

I would like to have the committee formed by May 1.

**Comment by khalidabuhakmeh** [comment]
@BillWagner how much time is each person on the committee expected to put into the nomination process? (sorry if the first question was unclear).

**Comment by BillWagner** [comment]
@wordshaker I believe this can be closed now. Would you agree?

**Comment by wordshaker** [comment]
@BillWagner Yup. I'll close it now
