### ISSUE TITLE
Determine the value proposition for membership

### ISSUE THREAD

**Issue by wordshaker** [dotnet-foundation/wg-membership#21]
## Brief Summary of idea

It's often asked what the value of being a member is beyond _"having your say on the future of the foundation"_. We need to determine the value proposition of benefits, both without financial impact and with financial impact. Are there any of these values we can strengthen?

## Aims / Benefits

- Increases transparency on why someone would want to be a member of the foundation/what the benefits are.

## Requirements

- [ ] Membership committee agree on a baseline value proposition
- [ ] Determine if this proposition changes between member participation types

**Comment by wordshaker** [comment]
@BillWagner  is this adequate for what we need to add to our Q2 goal? I'll add another issue around building community, but that might come after we have tackled this

**Comment by BillWagner** [comment]
I like this as a starting point. I'll add it to the agenda for our next meeting.

**Comment by wordshaker** [comment]
**Prerequisite knowledge for this work**
- From the board we need a view on the "goal" of the .NET Foundation. 
- What is the divide/responsibilities between Microsoft and the .NET Foundation?

**What we need to determine with this**
- What is the value prop for products/businesses
- What is the value prop for individual members

**Should our value proposition be based on people, community - not building a better tech system?**

**Comment by wordshaker** [comment]
@BillWagner need a catchup on the above and how we could get support from the Board

**Comment by khalidabuhakmeh** [comment]
Thoughts from a project member: https://www.theregister.com/2021/03/30/crossplatform_wpf_anyone_unpacking_avolonia/

**Comment by BillWagner** [comment]
The Membership Committee held a discussion on the .NET Foundation’s value proposition. The following ideas were discussed:

- Create “How to” guides for promoting the Foundation’s projects and encourage participation.
- Promote the new member participation types and their benefits on the website.
- Promote current member contributions from the community.
- Encourage more corporate member contributions to the Foundation to offset Microsoft’s contributions.
- Promote ways members can get involved in the community that can be rewarded.
- Teach members how to find a “good” issue or PR.

**Comment by wordshaker** [comment]
Worth revisiting after VMX is complete

**Comment by wordshaker** [comment]
Work has been done by the Board and the Committee is now discussing how to use Discord to provide greater member value
