### ISSUE TITLE
Strengthen and Build Community Culture

### ISSUE THREAD

**Issue by wordshaker** [dotnet-foundation/wg-membership#22]
## Brief Summary of idea

To determine what we want the culture of the .NET Foundations community to have and how to develop it. There are a lot of great minds doing exciting things. It would be great to foster this innovation, challenge, teaching and more by helping our members have a sense of community.

## Aims / Benefits

- This could be considered part of our value proposition 
- Better feedback and engagement from all members

## Requirements

- [ ] Determine what we want our culture to be/look like
- [ ] Outline community exchanges/activities/behaviours we would like to support (regardless of tooling)
- [ ] Develop a roadmap of how we can build such a community and tools we may want to trial as part of it.

**Comment by wordshaker** [comment]
**- Links to #21. Need to have a value proposition to build a community around**

**Extra notes:**
- Community to hear from the board on how it is going since they have joined and the main impacts they think the .NET Foundation has had? How their original goals are progressing/are they achievable? Maybe using videos. Different format from the emails and posts.

**Comment by BillWagner** [comment]
Thanks @wordshaker 

I'll get the conversation with the board rolling. I think we can drive it in the open, and also get input from our current and prospective members.
