### ISSUE TITLE
Rewording dues on website

### ISSUE THREAD

**Issue by wordshaker** [dotnet-foundation/wg-membership#30]
## Brief Summary of idea

The .[NET Foundation become a member page](https://dotnetfoundation.org/member) says:

`We’re requesting $100 annual dues, with liberal waivers for students or financial hardship. Dues are voluntary - you can set your own amount or opt-out entirely.`

The _"with liberal waivers for students or financial hardship"_ suggests to me that there is some process in getting a waiver (a form to fill, asking permission or something) which then contradicts the following line of _"Dues are voluntary - you can set your own amount or opt-out entirely."_

I would suggest removing _"with liberal waivers for students or financial hardship"_ 

## Aims / Benefits

- Clarity for those who can't or don't want to pay $100
- Removes deterrent for those who feel they would need to ask to not pay the full amount

## Requirements

Text on website is changed

**Comment by wordshaker** [comment]
@BillWagner who would be best to raise this with

**Comment by BillWagner** [comment]
@wordshaker 

Hmmm.  I fixed this in dotnet-foundation/website#902 (which has been merged).

@clairernovotny @isaacrlevin Any ideas why it's not live yet?

**Comment by clairernovotny** [comment]
Looks like it's live to me?

![image](https://user-images.githubusercontent.com/1427284/125448326-f5f606cb-5c07-4230-ab40-390ec801a46a.png)

**Comment by wordshaker** [comment]
Done a hard refresh and opened in incognito. How odd.

![Screenshot 2021-07-13 at 13 24 37](https://user-images.githubusercontent.com/13496774/125451056-c764dc80-7128-4d47-87e5-16b9434b8917.png)

https://dotnetfoundation.org/member

**Comment by BillWagner** [comment]
Same here.

I'll close this.

**Comment by clairernovotny** [comment]
Two different pages with the same wording. Looks like the change was only made to https://dotnetfoundation.org/member/become-a-member

**Comment by BillWagner** [comment]
Thanks @clairernovotny 

I just opened #917 to address this.

**Comment by wordshaker** [comment]
Thank you

**Comment by CalvinAllen** [comment]
@BillWagner Looks like this is complete / deployed; can we close?

**Comment by BillWagner** [comment]
Thanks. Closing now.
