### ISSUE TITLE
Proposal - Bug bounties for keeping foundation repository clean and updated

### ISSUE THREAD

**Issue by codehippie1** [dotnet-foundation/wg-membership#55]
## Brief Summary of idea

"Bug bounties" to .net foundation repo contributors to keep the repository clean and updated

## Aims / Benefits

Relevant and updated information is available on foundation repo

## Requirements

Proposal - Membership committee can have "bug bounties" among members and/or .net students(students working with education committee) to find issues and produce value within the foundation repos (Not talking about the OOS projects under foundation)

E.g. 
1. I have found out that link to speaker directory was missing/showing 404 in some pages. Find these sort of bugs
2. Add more relevant content/add value. E.g. - Add steps on "How to create a livestream event with .net foundation stream yard" under outreach
3. Design challenge for foundation mascot
4. UI/UX design challenge using figma/sketch/storybook on the Education committee's education portal displaying .net education content, we can take the winners design and build on top of it.

**Comment by wordshaker** [comment]
We currently don't have the budget for this.
