### ISSUE TITLE
.NET Foundation accredited courses?

### ISSUE THREAD

**Issue by wordshaker** [dotnet-foundation/wg-membership#7]
## Brief Summary of idea

- Bootcamps, apprenticeships and courses to get an accreditation/badge if they use resources provided by the .NET Foundation or Microsoft?

## Aims / Benefits

- Encourage more bootcamps to move to .NET
- Encourage more new blood into .NET and the .NET Foundation
- Badges can be put on their websites for visibility of .NET Foundation

## Requirements

Would need to decide if this is something we might want to do, how it would tie into membership tiers (maybe students?) and how it would work

**Comment by wordshaker** [comment]
This will probably be addressed by the Education Committee

**Comment by AraHaan** [comment]
I also know of somehow who has bootcamps on youtube as well (@Almantask) with his ``From Zero to Hero``. However his bootamps stopped for a bit due to covid and other issues (which you can ask him more information on).

**Comment by wordshaker** [comment]
Now an issue for the Education Committee
