### ISSUE TITLE
Membership Request - Jason Von Ruden

### ISSUE THREAD

**Issue by jvonruden** [dotnet-foundation/wg-membership#71]
## Your name: 
Jason Von Ruden

## Your Github Name or Email: 
jvonruden

## Projects:
I have expertise in promoting projects to the NET community. as a member of the .NET foundation since the beginning.  I am the President of the Wisconsin .NET User group with monthly meetings (even thru the 2020-present pandemic!) on .NET for the last 20 years: since February 12, 2002; formed one day before the the official NET release. 

https://www.wi-ineta.org/
https://www.meetup.com/wisconsin-net-users-group/
 
Thanks,

Jason Von Ruden

**Comment by wordshaker** [comment]
@BillWagner - want me to pick this up?

**Comment by samuelbarrionuevo** [comment]
> ## Your name:
> 
> Jason Von Ruden
> ## Your Github Name or Email:
> 
> jvonruden
> ## Projects:
> 
> I have expertise in promoting projects to the NET community. as a member of the .NET foundation since the beginning. I am the President of the Wisconsin .NET User group with monthly meetings (even thru the 2020-present pandemic!) on .NET for the last 20 years: since February 12, 2002; formed one day before the the official NET release.
> 
> https://www.wi-ineta.org/ https://www.meetup.com/wisconsin-net-users-group/
> 
> Thanks,
> 
> Jason Von Ruden

good, the members committee has a monthly or annual cost to join?

**Comment by wordshaker** [comment]
> > ## Your name:
> > Jason Von Ruden
> > ## Your Github Name or Email:
> > jvonruden
> > ## Projects:
> > I have expertise in promoting projects to the NET community. as a member of the .NET foundation since the beginning. I am the President of the Wisconsin .NET User group with monthly meetings (even thru the 2020-present pandemic!) on .NET for the last 20 years: since February 12, 2002; formed one day before the the official NET release.
> > https://www.wi-ineta.org/ https://www.meetup.com/wisconsin-net-users-group/
> > Thanks,
> > Jason Von Ruden
> 
> good, the members committee has a monthly or annual cost to join?

There is no cost to join. You need to be a member of the .NET Foundation and in the next meeting we will be discussing a membership charter for the committee to state expected levels of contribution 😄 hope this helps

**Comment by wordshaker** [comment]
Hello @jvonruden 

We have published our charter for the membership committee now. If you are happy with what is in there, comment on here and I'll add you to the teams and calendar invites

https://github.com/dotnet-foundation/wg-membership/blob/main/resources/commitee-documentation/membership-committee-charter.md

I'd be happy to answer any questions as well.

**Comment by jvonruden** [comment]
Looks good, I look forward to the next membership committee meeting!

**Comment by wordshaker** [comment]
I've requested that you be added to the invites and I'll add you to all the GitHub bits now. The next meeting is on the 4th Jan. Let me know if you do not recieve the invite before that date. 

Look forward to seeing you then! And thanks for your patience. Hope you have an enjoyable holiday period.

**Comment by jvonruden** [comment]
Hi Jessica,

My schedule has changed and on Wednesdays, I am not able to
attend/contribute during regularly scheduled Wednesday membership
meetings.

While I continue to be active on other .net foundation
committees including the education committee it does not make sense for me
to continue as an active member.

Jason Von Ruden
