### ISSUE TITLE
More information for board and committee responsibilities.

### ISSUE THREAD

**Issue by BillWagner** [dotnet-foundation/wg-membership#75]
See https://github.com/dotnet-foundation/wg-membership/pull/68#discussion_r980534045

This conversation captured important questions to update our list of board and committee responsibilities.

**Comment by wordshaker** [comment]
Would like to clarify with the committee
 
- [ ] Where should this information live? Where would it be most transparent and useful
- [ ] Who would like to draft documents for review

**Comment by wordshaker** [comment]
Can I close this @BillWagner or is it still an issue?
