### ISSUE TITLE
Nomination Committee Future Structure

### ISSUE THREAD

**Issue by wordshaker** [dotnet-foundation/wg-membership#81]
## Brief Summary of idea

@BillWagner has raised that the nomination committee selection and process happening for a short amount of months over the summer period has some negative impacts

- Availability is limited for members
- There isn't much time to select a committee
- Limited time for nomination committee to reach out to potential board candidates

It's been proposed that we either have a rolling nomination committee that does work throughout the year OR change the time for selecting a nomination committee to an earlier date and give them more time to conduct their actions

## Aims / Benefits

Better nomination process and more positive experience for those taking part

## Requirements

 Need to decide on a way forward and then take appropriate actions for arranging next years committee

**Comment by nicoleabuhakmeh** [comment]
I'd like to drop in the idea of having former board members be part of the next nomination committee.  I believe they would know where the gaps are that need filled in by members of the community.

**Comment by wordshaker** [comment]
Nomination Committee formed for this year based on the new proposed setup
