### ISSUE TITLE
Promotional Videos

### ISSUE THREAD

**Issue by wordshaker** [dotnet-foundation/wg-membership#83]
## Brief Summary of idea

A promotional short video for social media etc from our membership committee members on why they take part, what value and enjoyment they get out of the membership committee and promoting becoming a member of the .NET Foundation / Membership committee

## Aims / Benefits

Another way to promote the foundation and committee

## Requirements

We would need recordings and a decent edit.

**Comment by codehippie1** [comment]
+1 on this one.
Videos can be bite-sized as need be; for youtube shorts and such.
