### ISSUE TITLE
GitHub Teams Tidyup

### ISSUE THREAD

**Issue by wordshaker** [dotnet-foundation/wg-membership#84]
## Brief Summary of idea

The GitHub Team for the membership committee currently has 58 members which isn't reflective of the current participants
[Membership Committee Team](https://github.com/orgs/dotnet-foundation/teams/membership/members)

I propose a purge of accounts from this team (and would be happy to do the admin). For the next membership committee I would like to raise:

- Are we in agreement that this team should be trimmed down to those engaged in the committee?
- @nicoleabuhakmeh if we are in agreement that this Team should have some members removed, will we need to do wider comms about this action with a note on how to "re-sign up" for those who want to remain in the Team?

## Aims / Benefits

To reduce permissions granted to this repository to those that need it

## Requirements

Covered in the Brief

**Comment by nicoleabuhakmeh** [comment]
Yes and I can add it to:

- Newsletter for Nov 
- Message on Discord
- Message on Slack
- Message on Github
I'll let them know that we are completing that action, but we can reverse the action for anyone that speaks up.

**Comment by wordshaker** [comment]
Do we maybe also want to agree on a minimum engagement baseline for the group to remain on the GitHub team? Nothing too restrictive but at least a semi regular attendance to meetings or X amount of engagement on this repository.

https://github.com/dotnet-foundation/wg-membership/issues/71#issuecomment-1304879811

The idea is to ensure that those who have rights to edit the repo are engaging in the group discussions and to ensure that people aren't saying they are part of the committee without putting any time into it?

If we agree a baseline we can then make that clear in the README as well.

**Comment by wordshaker** [comment]
Removed all team members from [here](https://github.com/orgs/dotnet-foundation/teams/membership-committee/members) that are not either active members of the committee or members of the board
