### ISSUE TITLE
Archive existing DNF website repo

### ISSUE THREAD

**Issue by codehippie1** [dotnet-foundation/wg-membership#97]
## Brief Summary of the idea
Archive existing DNF website repo and provide a placeholder repo to create issues/proposals against the website.

## Requirements
Archive existing DNF website repo and provide a placeholder repo to create issues/proposals against the website.

**Comment by wordshaker** [comment]
Currently being persued by @jguadagno 
https://github.com/dotnet-foundation/website/pull/1216
